### ISSUE TITLE
electron-rebuild work failed

### ISSUE THREAD

**Issue by zkcrescent** [jooy2/vutron#135]
I use opencv4nodejs in vutron, and when I use `electron-rebuild` to rebuild opencv4nodejs, encountering error :

`

vutron/node_modules/cliui/build/index.cjs:293
const wrap = require('wrap-ansi');

 require() of ES Module vutron/node_modules/wrap-ansi/index.js from vutron/node_modules/cliui/build/index.cjs not supported
Instead change the require of index.js in vutron/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (vutron/node_modules/cliui/build/index.cjs:293:14)
    at Object.<anonymous> (vutron/node_modules/yargs/build/index.cjs:1:60678)
    at Object.<anonymous> (vutron/node_modules/yargs/yargs:3:69)
    at Object.<anonymous> (vutron/node_modules/@electron/rebuild/lib/cli.js:34:33) {
  code: 'ERR_REQUIRE_ESM'
}
`

I don't know how to fix it.

**Comment by zkcrescent** [comment]
I have fixed up question by rewrite cliui/build/index.cjs:293 to `const wrap = require('wrap-ansi-cjs');` and electron-rebuild works and I met another question. when I run `yarn dev` the below error shown：
```
ould not dynamically require "vutron/dist/build/Release/opencv4nodejs". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
```

and I found docs about  [dynamicRequireTargets] (https://github.com/rollup/plugins/tree/master/packages/commonjs#options) and set is as 

```
dynamicRequireTargets: ['opencv4nodejs"]
```

It didn't work.

It confused me the whole day.

**Comment by zkcrescent** [comment]
Add `@u4/opencv4nodejs` to `vite.config.ts` 

```
 electronPlugin([
        {
          entry: ['src/main/index.ts'],
          onstart: (options) => {
            options.startup()
          },
          vite: {
            build: {
              assetsDir: '.',
              outDir: 'dist/main',
              rollupOptions: {
                external: ['electron', '@u4/opencv4nodejs', ...builtinModules]
              },
              commonjsOptions: {
                  ignoreDynamicRequires: true,
              }
            }
          }
        },
        {
          entry: ['src/preload/index.ts'],
          onstart: (options) => {
            options.reload()
          },
          vite: {
            build: {
              outDir: 'dist/preload',
            },
          }
        }
      ]),

```
another error : 
```
dlopen(vutron/node_modules/@u4/opencv4nodejs/build/Release/opencv4nodejs.node, 0x0001): symbol not found in flat namespace '__ZNK2cv12MatAllocator23getBufferPoolControllerEPKc'
```
- - It's so hard to me to fix these unknown errors.

**Comment by zkcrescent** [comment]
I fixed this problem by install opencv by `opencv4nodejs auto-install ` ! 

works fine now. 

closed.
